### ISSUE TITLE
Either complete "imageURL" feature or remove the property

### ISSUE THREAD

**Issue by jpmcglone** [Imgur/Hermes#3]
Asynchronously load an image from the web if 'imageURL' is set.   Probably using SDWebImage.

**Comment by matt-lebl** [comment]
You could also go for an all-Swift approach (keeping true to Hermes' all-Swiftiness) and use Alamofire, or if you don't want extra libraries you could simply use `NSURLSession`.

``` swift
// Define the URL to the image (this is the imageURL attribute in HermesNotification.swift)
let imageURL = NSURL(string: "http://i.imgur.com/gjzeE3Z.png/")

// Using NSURLSession API to fetch image
// You might choose to change the NSURLConfiguration to add things like timeouts and cellular configuration
let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
let session = NSURLSession(configuration: configuration)

// NSURLRequest Object
let request = NSURLRequest(URL: imageURL!)

let dataTask = session.dataTaskWithRequest(request, completionHandler: { (data: NSData!, response: NSURLResponse!, error: NSError!) -> Void in
    if error == nil {
        // Set whatever image attribute to the returned data
        self.image = UIImage(data: data)!
    } else {
        println(error)
    }
})

// Start the data task
dataTask.resume()
```

This has the advantage of being asynchronous, with all-Swift code, without adding unnecessary libraries.

**Comment by jpmcglone** [comment]
Good idea :) I'm still exhausted from this weekend (Camp Imgur!) And will be catching up on a lot of work work this week.  I'll do my very best to squeeze this one in within the next few days though.  Thanks for the idea!  We could always iterate on it later.

**Comment by matt-lebl** [comment]
:+1:
