### ISSUE TITLE
Swift 2.0 Support

### ISSUE THREAD

**Issue by focusedonfit** [Imgur/Hermes#5]
Will there be a branch for Swift 2.0 support?

Thank you

**Comment by jpmcglone** [comment]
There will definitely be, since we plan on moving our app to 2.0 and will need it :P  Not sure on the timeline. Will try to do it sooner than later, but I encourage anybody to submit a pull request (I can approve that more quickly)

**Comment by matt-lebl** [comment]
The Xcode autoconvert seems to work okay, [I tried it on my fork.](https://github.com/blerchy/Hermes/tree/swift2) Let me know if you see anything amiss, I'll look into it. After that it's just a matter of utilizing the new tools in Swift 2.0 :smirk:

**Comment by jpmcglone** [comment]
Looks good to me. I'll try to get the same done here when I have some free time.  Thanks for trying that :D

**Comment by jpmcglone** [comment]
I made the swift 2.0 branch.  Question for you guys, moving forward, nobody's expecting both the 1.2 and 2.0 branch to be supported right?  I'm pretty certain I'm going to make the 2.0 branch 'master' when 2.0 is officially out.  Not sure what most of the community is doing though.

**Comment by matt-lebl** [comment]
I doubt anyone's expecting the pre-2.0 to be supported _officially_ once 2.0 comes out. However, you can allow the community to port updates moving forward to a "pre-2.0" branch.

**Comment by jpmcglone** [comment]
:+1:
